/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.rpl.mastodon.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class AccountContent extends org.apache.thrift.TUnion<AccountContent, AccountContent._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AccountContent");
  private static final org.apache.thrift.protocol.TField LOCAL_FIELD_DESC = new org.apache.thrift.protocol.TField("local", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField REMOTE_FIELD_DESC = new org.apache.thrift.protocol.TField("remote", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LOCAL((short)1, "local"),
    REMOTE((short)2, "remote");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LOCAL
          return LOCAL;
        case 2: // REMOTE
          return REMOTE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LOCAL, new org.apache.thrift.meta_data.FieldMetaData("local", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LocalAccount.class)));
    tmpMap.put(_Fields.REMOTE, new org.apache.thrift.meta_data.FieldMetaData("remote", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, RemoteAccount.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AccountContent.class, metaDataMap);
  }

  public AccountContent() {
    super();
  }

  public AccountContent(_Fields setField, java.lang.Object value) {
    super(setField, value);
  }

  public AccountContent(AccountContent other) {
    super(other);
  }
  @Override
  public AccountContent deepCopy() {
    return new AccountContent(this);
  }

  public static AccountContent local(LocalAccount value) {
    AccountContent x = new AccountContent();
    x.setLocal(value);
    return x;
  }

  public static AccountContent remote(RemoteAccount value) {
    AccountContent x = new AccountContent();
    x.setRemote(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, java.lang.Object value) throws java.lang.ClassCastException {
    switch (setField) {
      case LOCAL:
        if (value instanceof LocalAccount) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type LocalAccount for field 'local', but got " + value.getClass().getSimpleName());
      case REMOTE:
        if (value instanceof RemoteAccount) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type RemoteAccount for field 'remote', but got " + value.getClass().getSimpleName());
      default:
        throw new java.lang.IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected java.lang.Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case LOCAL:
          if (field.type == LOCAL_FIELD_DESC.type) {
            LocalAccount local;
            local = new LocalAccount();
            local.read(iprot);
            return local;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case REMOTE:
          if (field.type == REMOTE_FIELD_DESC.type) {
            RemoteAccount remote;
            remote = new RemoteAccount();
            remote.read(iprot);
            return remote;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new java.lang.IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case LOCAL:
        LocalAccount local = (LocalAccount)value_;
        local.write(oprot);
        return;
      case REMOTE:
        RemoteAccount remote = (RemoteAccount)value_;
        remote.write(oprot);
        return;
      default:
        throw new java.lang.IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected java.lang.Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case LOCAL:
          LocalAccount local;
          local = new LocalAccount();
          local.read(iprot);
          return local;
        case REMOTE:
          RemoteAccount remote;
          remote = new RemoteAccount();
          remote.read(iprot);
          return remote;
        default:
          throw new java.lang.IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new org.apache.thrift.protocol.TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case LOCAL:
        LocalAccount local = (LocalAccount)value_;
        local.write(oprot);
        return;
      case REMOTE:
        RemoteAccount remote = (RemoteAccount)value_;
        remote.write(oprot);
        return;
      default:
        throw new java.lang.IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case LOCAL:
        return LOCAL_FIELD_DESC;
      case REMOTE:
        return REMOTE_FIELD_DESC;
      default:
        throw new java.lang.IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public LocalAccount getLocal() {
    if (getSetField() == _Fields.LOCAL) {
      return (LocalAccount)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'local' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setLocal(LocalAccount value) {
    setField_ = _Fields.LOCAL;
    value_ = java.util.Objects.requireNonNull(value,"_Fields.LOCAL");
  }

  public RemoteAccount getRemote() {
    if (getSetField() == _Fields.REMOTE) {
      return (RemoteAccount)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'remote' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setRemote(RemoteAccount value) {
    setField_ = _Fields.REMOTE;
    value_ = java.util.Objects.requireNonNull(value,"_Fields.REMOTE");
  }

  public boolean isSetLocal() {
    return setField_ == _Fields.LOCAL;
  }


  public boolean isSetRemote() {
    return setField_ == _Fields.REMOTE;
  }


  public boolean equals(java.lang.Object other) {
    if (other instanceof AccountContent) {
      return equals((AccountContent)other);
    } else {
      return false;
    }
  }

  public boolean equals(AccountContent other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(AccountContent other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    java.util.List<java.lang.Object> list = new java.util.ArrayList<java.lang.Object>();
    list.add(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      list.add(setField.getThriftFieldId());
      java.lang.Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        list.add(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        list.add(value);
      }
    }
    return list.hashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
