/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.rpl.mastodon.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class Conversation implements org.apache.thrift.TBase<Conversation, Conversation._Fields>, java.io.Serializable, Cloneable, Comparable<Conversation> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Conversation");

  private static final org.apache.thrift.protocol.TField CONVERSATION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("conversationId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField UNREAD_FIELD_DESC = new org.apache.thrift.protocol.TField("unread", org.apache.thrift.protocol.TType.BOOL, (short)2);
  private static final org.apache.thrift.protocol.TField ACCOUNTS_FIELD_DESC = new org.apache.thrift.protocol.TField("accounts", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField LAST_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("lastStatus", org.apache.thrift.protocol.TType.STRUCT, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ConversationStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ConversationTupleSchemeFactory();

  public long conversationId; // required
  public boolean unread; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<AccountWithId> accounts; // required
  public @org.apache.thrift.annotation.Nullable StatusQueryResult lastStatus; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CONVERSATION_ID((short)1, "conversationId"),
    UNREAD((short)2, "unread"),
    ACCOUNTS((short)3, "accounts"),
    LAST_STATUS((short)4, "lastStatus");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CONVERSATION_ID
          return CONVERSATION_ID;
        case 2: // UNREAD
          return UNREAD;
        case 3: // ACCOUNTS
          return ACCOUNTS;
        case 4: // LAST_STATUS
          return LAST_STATUS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CONVERSATIONID_ISSET_ID = 0;
  private static final int __UNREAD_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.LAST_STATUS};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CONVERSATION_ID, new org.apache.thrift.meta_data.FieldMetaData("conversationId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "ConversationId")));
    tmpMap.put(_Fields.UNREAD, new org.apache.thrift.meta_data.FieldMetaData("unread", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.ACCOUNTS, new org.apache.thrift.meta_data.FieldMetaData("accounts", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, AccountWithId.class))));
    tmpMap.put(_Fields.LAST_STATUS, new org.apache.thrift.meta_data.FieldMetaData("lastStatus", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, StatusQueryResult.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Conversation.class, metaDataMap);
  }

  public Conversation() {
  }

  public Conversation(
    long conversationId,
    boolean unread,
    java.util.List<AccountWithId> accounts)
  {
    this();
    this.conversationId = conversationId;
    setConversationIdIsSet(true);
    this.unread = unread;
    setUnreadIsSet(true);
    this.accounts = accounts;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Conversation(Conversation other) {
    __isset_bitfield = other.__isset_bitfield;
    this.conversationId = other.conversationId;
    this.unread = other.unread;
    if (other.isSetAccounts()) {
      java.util.List<AccountWithId> __this__accounts = new java.util.ArrayList<AccountWithId>(other.accounts.size());
      for (AccountWithId other_element : other.accounts) {
        __this__accounts.add(new AccountWithId(other_element));
      }
      this.accounts = __this__accounts;
    }
    if (other.isSetLastStatus()) {
      this.lastStatus = new StatusQueryResult(other.lastStatus);
    }
  }

  @Override
  public Conversation deepCopy() {
    return new Conversation(this);
  }

  @Override
  public void clear() {
    setConversationIdIsSet(false);
    this.conversationId = 0;
    setUnreadIsSet(false);
    this.unread = false;
    this.accounts = null;
    this.lastStatus = null;
  }

  public long getConversationId() {
    return this.conversationId;
  }

  public Conversation setConversationId(long conversationId) {
    this.conversationId = conversationId;
    setConversationIdIsSet(true);
    return this;
  }

  public void unsetConversationId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CONVERSATIONID_ISSET_ID);
  }

  /** Returns true if field conversationId is set (has been assigned a value) and false otherwise */
  public boolean isSetConversationId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CONVERSATIONID_ISSET_ID);
  }

  public void setConversationIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CONVERSATIONID_ISSET_ID, value);
  }

  public boolean isUnread() {
    return this.unread;
  }

  public Conversation setUnread(boolean unread) {
    this.unread = unread;
    setUnreadIsSet(true);
    return this;
  }

  public void unsetUnread() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __UNREAD_ISSET_ID);
  }

  /** Returns true if field unread is set (has been assigned a value) and false otherwise */
  public boolean isSetUnread() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __UNREAD_ISSET_ID);
  }

  public void setUnreadIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __UNREAD_ISSET_ID, value);
  }

  public int getAccountsSize() {
    return (this.accounts == null) ? 0 : this.accounts.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<AccountWithId> getAccountsIterator() {
    return (this.accounts == null) ? null : this.accounts.iterator();
  }

  public void addToAccounts(AccountWithId elem) {
    if (this.accounts == null) {
      this.accounts = new java.util.ArrayList<AccountWithId>();
    }
    this.accounts.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<AccountWithId> getAccounts() {
    return this.accounts;
  }

  public Conversation setAccounts(@org.apache.thrift.annotation.Nullable java.util.List<AccountWithId> accounts) {
    this.accounts = accounts;
    return this;
  }

  public void unsetAccounts() {
    this.accounts = null;
  }

  /** Returns true if field accounts is set (has been assigned a value) and false otherwise */
  public boolean isSetAccounts() {
    return this.accounts != null;
  }

  public void setAccountsIsSet(boolean value) {
    if (!value) {
      this.accounts = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public StatusQueryResult getLastStatus() {
    return this.lastStatus;
  }

  public Conversation setLastStatus(@org.apache.thrift.annotation.Nullable StatusQueryResult lastStatus) {
    this.lastStatus = lastStatus;
    return this;
  }

  public void unsetLastStatus() {
    this.lastStatus = null;
  }

  /** Returns true if field lastStatus is set (has been assigned a value) and false otherwise */
  public boolean isSetLastStatus() {
    return this.lastStatus != null;
  }

  public void setLastStatusIsSet(boolean value) {
    if (!value) {
      this.lastStatus = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case CONVERSATION_ID:
      if (value == null) {
        unsetConversationId();
      } else {
        setConversationId((java.lang.Long)value);
      }
      break;

    case UNREAD:
      if (value == null) {
        unsetUnread();
      } else {
        setUnread((java.lang.Boolean)value);
      }
      break;

    case ACCOUNTS:
      if (value == null) {
        unsetAccounts();
      } else {
        setAccounts((java.util.List<AccountWithId>)value);
      }
      break;

    case LAST_STATUS:
      if (value == null) {
        unsetLastStatus();
      } else {
        setLastStatus((StatusQueryResult)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CONVERSATION_ID:
      return getConversationId();

    case UNREAD:
      return isUnread();

    case ACCOUNTS:
      return getAccounts();

    case LAST_STATUS:
      return getLastStatus();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CONVERSATION_ID:
      return isSetConversationId();
    case UNREAD:
      return isSetUnread();
    case ACCOUNTS:
      return isSetAccounts();
    case LAST_STATUS:
      return isSetLastStatus();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof Conversation)
      return this.equals((Conversation)that);
    return false;
  }

  public boolean equals(Conversation that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_conversationId = true;
    boolean that_present_conversationId = true;
    if (this_present_conversationId || that_present_conversationId) {
      if (!(this_present_conversationId && that_present_conversationId))
        return false;
      if (this.conversationId != that.conversationId)
        return false;
    }

    boolean this_present_unread = true;
    boolean that_present_unread = true;
    if (this_present_unread || that_present_unread) {
      if (!(this_present_unread && that_present_unread))
        return false;
      if (this.unread != that.unread)
        return false;
    }

    boolean this_present_accounts = true && this.isSetAccounts();
    boolean that_present_accounts = true && that.isSetAccounts();
    if (this_present_accounts || that_present_accounts) {
      if (!(this_present_accounts && that_present_accounts))
        return false;
      if (!this.accounts.equals(that.accounts))
        return false;
    }

    boolean this_present_lastStatus = true && this.isSetLastStatus();
    boolean that_present_lastStatus = true && that.isSetLastStatus();
    if (this_present_lastStatus || that_present_lastStatus) {
      if (!(this_present_lastStatus && that_present_lastStatus))
        return false;
      if (!this.lastStatus.equals(that.lastStatus))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(conversationId);

    hashCode = hashCode * 8191 + ((unread) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetAccounts()) ? 131071 : 524287);
    if (isSetAccounts())
      hashCode = hashCode * 8191 + accounts.hashCode();

    hashCode = hashCode * 8191 + ((isSetLastStatus()) ? 131071 : 524287);
    if (isSetLastStatus())
      hashCode = hashCode * 8191 + lastStatus.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Conversation other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetConversationId(), other.isSetConversationId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetConversationId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.conversationId, other.conversationId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetUnread(), other.isSetUnread());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUnread()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.unread, other.unread);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAccounts(), other.isSetAccounts());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAccounts()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accounts, other.accounts);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLastStatus(), other.isSetLastStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastStatus, other.lastStatus);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Conversation(");
    boolean first = true;

    sb.append("conversationId:");
    sb.append(this.conversationId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("unread:");
    sb.append(this.unread);
    first = false;
    if (!first) sb.append(", ");
    sb.append("accounts:");
    if (this.accounts == null) {
      sb.append("null");
    } else {
      sb.append(this.accounts);
    }
    first = false;
    if (isSetLastStatus()) {
      if (!first) sb.append(", ");
      sb.append("lastStatus:");
      if (this.lastStatus == null) {
        sb.append("null");
      } else {
        sb.append(this.lastStatus);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'conversationId' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'unread' because it's a primitive and you chose the non-beans generator.
    if (accounts == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'accounts' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (lastStatus != null) {
      lastStatus.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ConversationStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ConversationStandardScheme getScheme() {
      return new ConversationStandardScheme();
    }
  }

  private static class ConversationStandardScheme extends org.apache.thrift.scheme.StandardScheme<Conversation> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, Conversation struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CONVERSATION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.conversationId = iprot.readI64();
              struct.setConversationIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // UNREAD
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.unread = iprot.readBool();
              struct.setUnreadIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ACCOUNTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list174 = iprot.readListBegin();
                struct.accounts = new java.util.ArrayList<AccountWithId>(_list174.size);
                @org.apache.thrift.annotation.Nullable AccountWithId _elem175;
                for (int _i176 = 0; _i176 < _list174.size; ++_i176)
                {
                  _elem175 = new AccountWithId();
                  _elem175.read(iprot);
                  struct.accounts.add(_elem175);
                }
                iprot.readListEnd();
              }
              struct.setAccountsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // LAST_STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.lastStatus = new StatusQueryResult();
              struct.lastStatus.read(iprot);
              struct.setLastStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetConversationId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'conversationId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetUnread()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'unread' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, Conversation struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(CONVERSATION_ID_FIELD_DESC);
      oprot.writeI64(struct.conversationId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(UNREAD_FIELD_DESC);
      oprot.writeBool(struct.unread);
      oprot.writeFieldEnd();
      if (struct.accounts != null) {
        oprot.writeFieldBegin(ACCOUNTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.accounts.size()));
          for (AccountWithId _iter177 : struct.accounts)
          {
            _iter177.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.lastStatus != null) {
        if (struct.isSetLastStatus()) {
          oprot.writeFieldBegin(LAST_STATUS_FIELD_DESC);
          struct.lastStatus.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ConversationTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ConversationTupleScheme getScheme() {
      return new ConversationTupleScheme();
    }
  }

  private static class ConversationTupleScheme extends org.apache.thrift.scheme.TupleScheme<Conversation> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Conversation struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI64(struct.conversationId);
      oprot.writeBool(struct.unread);
      {
        oprot.writeI32(struct.accounts.size());
        for (AccountWithId _iter178 : struct.accounts)
        {
          _iter178.write(oprot);
        }
      }
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetLastStatus()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetLastStatus()) {
        struct.lastStatus.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Conversation struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.conversationId = iprot.readI64();
      struct.setConversationIdIsSet(true);
      struct.unread = iprot.readBool();
      struct.setUnreadIsSet(true);
      {
        org.apache.thrift.protocol.TList _list179 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
        struct.accounts = new java.util.ArrayList<AccountWithId>(_list179.size);
        @org.apache.thrift.annotation.Nullable AccountWithId _elem180;
        for (int _i181 = 0; _i181 < _list179.size; ++_i181)
        {
          _elem180 = new AccountWithId();
          _elem180.read(iprot);
          struct.accounts.add(_elem180);
        }
      }
      struct.setAccountsIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.lastStatus = new StatusQueryResult();
        struct.lastStatus.read(iprot);
        struct.setLastStatusIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

