/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.rpl.mastodon.data;


public enum FanoutAction implements org.apache.thrift.TEnum {
  Add(1),
  Edit(2),
  Remove(3);

  private final int value;

  private FanoutAction(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static FanoutAction findByValue(int value) { 
    switch (value) {
      case 1:
        return Add;
      case 2:
        return Edit;
      case 3:
        return Remove;
      default:
        return null;
    }
  }
}
