/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.rpl.mastodon.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class Follower implements org.apache.thrift.TBase<Follower, Follower._Fields>, java.io.Serializable, Cloneable, Comparable<Follower> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Follower");

  private static final org.apache.thrift.protocol.TField ACCOUNT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("accountId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField SHOW_BOOSTS_FIELD_DESC = new org.apache.thrift.protocol.TField("showBoosts", org.apache.thrift.protocol.TType.BOOL, (short)2);
  private static final org.apache.thrift.protocol.TField LANGUAGES_FIELD_DESC = new org.apache.thrift.protocol.TField("languages", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField SHARED_INBOX_URL_FIELD_DESC = new org.apache.thrift.protocol.TField("sharedInboxUrl", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new FollowerStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new FollowerTupleSchemeFactory();

  public long accountId; // required
  public boolean showBoosts; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> languages; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String sharedInboxUrl; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ACCOUNT_ID((short)1, "accountId"),
    SHOW_BOOSTS((short)2, "showBoosts"),
    LANGUAGES((short)3, "languages"),
    SHARED_INBOX_URL((short)4, "sharedInboxUrl");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ACCOUNT_ID
          return ACCOUNT_ID;
        case 2: // SHOW_BOOSTS
          return SHOW_BOOSTS;
        case 3: // LANGUAGES
          return LANGUAGES;
        case 4: // SHARED_INBOX_URL
          return SHARED_INBOX_URL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ACCOUNTID_ISSET_ID = 0;
  private static final int __SHOWBOOSTS_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.LANGUAGES,_Fields.SHARED_INBOX_URL};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ACCOUNT_ID, new org.apache.thrift.meta_data.FieldMetaData("accountId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "AccountId")));
    tmpMap.put(_Fields.SHOW_BOOSTS, new org.apache.thrift.meta_data.FieldMetaData("showBoosts", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.LANGUAGES, new org.apache.thrift.meta_data.FieldMetaData("languages", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.SHARED_INBOX_URL, new org.apache.thrift.meta_data.FieldMetaData("sharedInboxUrl", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Follower.class, metaDataMap);
  }

  public Follower() {
  }

  public Follower(
    long accountId,
    boolean showBoosts)
  {
    this();
    this.accountId = accountId;
    setAccountIdIsSet(true);
    this.showBoosts = showBoosts;
    setShowBoostsIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Follower(Follower other) {
    __isset_bitfield = other.__isset_bitfield;
    this.accountId = other.accountId;
    this.showBoosts = other.showBoosts;
    if (other.isSetLanguages()) {
      java.util.List<java.lang.String> __this__languages = new java.util.ArrayList<java.lang.String>(other.languages);
      this.languages = __this__languages;
    }
    if (other.isSetSharedInboxUrl()) {
      this.sharedInboxUrl = other.sharedInboxUrl;
    }
  }

  @Override
  public Follower deepCopy() {
    return new Follower(this);
  }

  @Override
  public void clear() {
    setAccountIdIsSet(false);
    this.accountId = 0;
    setShowBoostsIsSet(false);
    this.showBoosts = false;
    this.languages = null;
    this.sharedInboxUrl = null;
  }

  public long getAccountId() {
    return this.accountId;
  }

  public Follower setAccountId(long accountId) {
    this.accountId = accountId;
    setAccountIdIsSet(true);
    return this;
  }

  public void unsetAccountId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ACCOUNTID_ISSET_ID);
  }

  /** Returns true if field accountId is set (has been assigned a value) and false otherwise */
  public boolean isSetAccountId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ACCOUNTID_ISSET_ID);
  }

  public void setAccountIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ACCOUNTID_ISSET_ID, value);
  }

  public boolean isShowBoosts() {
    return this.showBoosts;
  }

  public Follower setShowBoosts(boolean showBoosts) {
    this.showBoosts = showBoosts;
    setShowBoostsIsSet(true);
    return this;
  }

  public void unsetShowBoosts() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SHOWBOOSTS_ISSET_ID);
  }

  /** Returns true if field showBoosts is set (has been assigned a value) and false otherwise */
  public boolean isSetShowBoosts() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SHOWBOOSTS_ISSET_ID);
  }

  public void setShowBoostsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SHOWBOOSTS_ISSET_ID, value);
  }

  public int getLanguagesSize() {
    return (this.languages == null) ? 0 : this.languages.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.String> getLanguagesIterator() {
    return (this.languages == null) ? null : this.languages.iterator();
  }

  public void addToLanguages(java.lang.String elem) {
    if (this.languages == null) {
      this.languages = new java.util.ArrayList<java.lang.String>();
    }
    this.languages.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.String> getLanguages() {
    return this.languages;
  }

  public Follower setLanguages(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> languages) {
    this.languages = languages;
    return this;
  }

  public void unsetLanguages() {
    this.languages = null;
  }

  /** Returns true if field languages is set (has been assigned a value) and false otherwise */
  public boolean isSetLanguages() {
    return this.languages != null;
  }

  public void setLanguagesIsSet(boolean value) {
    if (!value) {
      this.languages = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getSharedInboxUrl() {
    return this.sharedInboxUrl;
  }

  public Follower setSharedInboxUrl(@org.apache.thrift.annotation.Nullable java.lang.String sharedInboxUrl) {
    this.sharedInboxUrl = sharedInboxUrl;
    return this;
  }

  public void unsetSharedInboxUrl() {
    this.sharedInboxUrl = null;
  }

  /** Returns true if field sharedInboxUrl is set (has been assigned a value) and false otherwise */
  public boolean isSetSharedInboxUrl() {
    return this.sharedInboxUrl != null;
  }

  public void setSharedInboxUrlIsSet(boolean value) {
    if (!value) {
      this.sharedInboxUrl = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ACCOUNT_ID:
      if (value == null) {
        unsetAccountId();
      } else {
        setAccountId((java.lang.Long)value);
      }
      break;

    case SHOW_BOOSTS:
      if (value == null) {
        unsetShowBoosts();
      } else {
        setShowBoosts((java.lang.Boolean)value);
      }
      break;

    case LANGUAGES:
      if (value == null) {
        unsetLanguages();
      } else {
        setLanguages((java.util.List<java.lang.String>)value);
      }
      break;

    case SHARED_INBOX_URL:
      if (value == null) {
        unsetSharedInboxUrl();
      } else {
        setSharedInboxUrl((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ACCOUNT_ID:
      return getAccountId();

    case SHOW_BOOSTS:
      return isShowBoosts();

    case LANGUAGES:
      return getLanguages();

    case SHARED_INBOX_URL:
      return getSharedInboxUrl();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ACCOUNT_ID:
      return isSetAccountId();
    case SHOW_BOOSTS:
      return isSetShowBoosts();
    case LANGUAGES:
      return isSetLanguages();
    case SHARED_INBOX_URL:
      return isSetSharedInboxUrl();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof Follower)
      return this.equals((Follower)that);
    return false;
  }

  public boolean equals(Follower that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_accountId = true;
    boolean that_present_accountId = true;
    if (this_present_accountId || that_present_accountId) {
      if (!(this_present_accountId && that_present_accountId))
        return false;
      if (this.accountId != that.accountId)
        return false;
    }

    boolean this_present_showBoosts = true;
    boolean that_present_showBoosts = true;
    if (this_present_showBoosts || that_present_showBoosts) {
      if (!(this_present_showBoosts && that_present_showBoosts))
        return false;
      if (this.showBoosts != that.showBoosts)
        return false;
    }

    boolean this_present_languages = true && this.isSetLanguages();
    boolean that_present_languages = true && that.isSetLanguages();
    if (this_present_languages || that_present_languages) {
      if (!(this_present_languages && that_present_languages))
        return false;
      if (!this.languages.equals(that.languages))
        return false;
    }

    boolean this_present_sharedInboxUrl = true && this.isSetSharedInboxUrl();
    boolean that_present_sharedInboxUrl = true && that.isSetSharedInboxUrl();
    if (this_present_sharedInboxUrl || that_present_sharedInboxUrl) {
      if (!(this_present_sharedInboxUrl && that_present_sharedInboxUrl))
        return false;
      if (!this.sharedInboxUrl.equals(that.sharedInboxUrl))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(accountId);

    hashCode = hashCode * 8191 + ((showBoosts) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetLanguages()) ? 131071 : 524287);
    if (isSetLanguages())
      hashCode = hashCode * 8191 + languages.hashCode();

    hashCode = hashCode * 8191 + ((isSetSharedInboxUrl()) ? 131071 : 524287);
    if (isSetSharedInboxUrl())
      hashCode = hashCode * 8191 + sharedInboxUrl.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Follower other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetAccountId(), other.isSetAccountId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAccountId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accountId, other.accountId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetShowBoosts(), other.isSetShowBoosts());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetShowBoosts()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.showBoosts, other.showBoosts);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLanguages(), other.isSetLanguages());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLanguages()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.languages, other.languages);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSharedInboxUrl(), other.isSetSharedInboxUrl());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSharedInboxUrl()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sharedInboxUrl, other.sharedInboxUrl);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Follower(");
    boolean first = true;

    sb.append("accountId:");
    sb.append(this.accountId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("showBoosts:");
    sb.append(this.showBoosts);
    first = false;
    if (isSetLanguages()) {
      if (!first) sb.append(", ");
      sb.append("languages:");
      if (this.languages == null) {
        sb.append("null");
      } else {
        sb.append(this.languages);
      }
      first = false;
    }
    if (isSetSharedInboxUrl()) {
      if (!first) sb.append(", ");
      sb.append("sharedInboxUrl:");
      if (this.sharedInboxUrl == null) {
        sb.append("null");
      } else {
        sb.append(this.sharedInboxUrl);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'accountId' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'showBoosts' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FollowerStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public FollowerStandardScheme getScheme() {
      return new FollowerStandardScheme();
    }
  }

  private static class FollowerStandardScheme extends org.apache.thrift.scheme.StandardScheme<Follower> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, Follower struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ACCOUNT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.accountId = iprot.readI64();
              struct.setAccountIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SHOW_BOOSTS
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.showBoosts = iprot.readBool();
              struct.setShowBoostsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // LANGUAGES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list28 = iprot.readListBegin();
                struct.languages = new java.util.ArrayList<java.lang.String>(_list28.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _elem29;
                for (int _i30 = 0; _i30 < _list28.size; ++_i30)
                {
                  _elem29 = iprot.readString();
                  struct.languages.add(_elem29);
                }
                iprot.readListEnd();
              }
              struct.setLanguagesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // SHARED_INBOX_URL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.sharedInboxUrl = iprot.readString();
              struct.setSharedInboxUrlIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetAccountId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'accountId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetShowBoosts()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'showBoosts' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, Follower struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ACCOUNT_ID_FIELD_DESC);
      oprot.writeI64(struct.accountId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SHOW_BOOSTS_FIELD_DESC);
      oprot.writeBool(struct.showBoosts);
      oprot.writeFieldEnd();
      if (struct.languages != null) {
        if (struct.isSetLanguages()) {
          oprot.writeFieldBegin(LANGUAGES_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.languages.size()));
            for (java.lang.String _iter31 : struct.languages)
            {
              oprot.writeString(_iter31);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.sharedInboxUrl != null) {
        if (struct.isSetSharedInboxUrl()) {
          oprot.writeFieldBegin(SHARED_INBOX_URL_FIELD_DESC);
          oprot.writeString(struct.sharedInboxUrl);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FollowerTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public FollowerTupleScheme getScheme() {
      return new FollowerTupleScheme();
    }
  }

  private static class FollowerTupleScheme extends org.apache.thrift.scheme.TupleScheme<Follower> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Follower struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI64(struct.accountId);
      oprot.writeBool(struct.showBoosts);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetLanguages()) {
        optionals.set(0);
      }
      if (struct.isSetSharedInboxUrl()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetLanguages()) {
        {
          oprot.writeI32(struct.languages.size());
          for (java.lang.String _iter32 : struct.languages)
          {
            oprot.writeString(_iter32);
          }
        }
      }
      if (struct.isSetSharedInboxUrl()) {
        oprot.writeString(struct.sharedInboxUrl);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Follower struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.accountId = iprot.readI64();
      struct.setAccountIdIsSet(true);
      struct.showBoosts = iprot.readBool();
      struct.setShowBoostsIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list33 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
          struct.languages = new java.util.ArrayList<java.lang.String>(_list33.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _elem34;
          for (int _i35 = 0; _i35 < _list33.size; ++_i35)
          {
            _elem34 = iprot.readString();
            struct.languages.add(_elem34);
          }
        }
        struct.setLanguagesIsSet(true);
      }
      if (incoming.get(1)) {
        struct.sharedInboxUrl = iprot.readString();
        struct.setSharedInboxUrlIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

